### ISSUE TITLE
TS2307: Cannot find module '@adminjs/mongoose' or its corresponding type declarations.

### ISSUE THREAD

**Issue by pranavburnwal** [SoftwareBrothers/adminjs-mongoose#107]
Version tried: 
[4.0.0](https://www.npmjs.com/package/@adminjs/mongoose/v/4.0.0)
[4.0.0-beta.4](https://www.npmjs.com/package/@adminjs/mongoose/v/4.0.0-beta.4)

```
    "@adminjs/express": "^6.0.0",
    "@adminjs/mongoose": "4.0.0",
    "adminjs": "^7.1.0",
```

`tsconfig.json`
```
{
    "compilerOptions": {
        "module": "commonjs",
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "target": "ESNext",
        "noImplicitAny": true,
        "moduleResolution": "node",
	.....
	}
}
```

<img width="924" alt="image" src="https://github.com/SoftwareBrothers/adminjs-mongoose/assets/15976005/14659b6d-e25a-45d2-828f-f3eb70f29cc6">

Thanks in advance!

Edit: Added other companion module versions

**Comment by dziraf** [comment]
The latest versions of AdminJS support only ESM projects, this is mentioned in the documentation: https://docs.adminjs.co/installation/getting-started#esm-and-cjs-support
