### ISSUE TITLE
Does this plugin work with mongoose encryption plugins?

### ISSUE THREAD

**Issue by Thecave3** [SoftwareBrothers/adminjs-mongoose#35]
Hello,

thank you for your work. I was wondering if your software works with plugins that encrypt the values of the DB such as [mongoose-encryption](https://www.npmjs.com/package/mongoose-encryption) or [mongoose-field-encryption](https://www.npmjs.com/package/mongoose-field-encryption).

Since according to the European GDPR databases have to be encrypted such tools are becoming quite mandatory.

Thank you for the attention

**Comment by wojtek-krysiak** [comment]
tbh - I don't know - you will have to check it out

**Comment by Thecave3** [comment]
I'm gonna run some tests and post here the results. In principle, if this software uses the classic mongoose operations it should already load the plugins.

Gonne keep this open
